### PR TITLE
Fix typo on dismissal var.dismiss_review_users variable

### PR DESCRIPTION
**Pull request by rahardiandj**
Failed to do terraform init due to this typo, create PR to fix this

### CODE REVIEW

**Comment by salvianreynaldi** [comment]
Hi @rahardiandj, thanks for the PR!
However, the line is intentional and just updated recently in #15 to support terraform 0.12
If you still use terraform v0.11.x, please use v1.0.0

**Comment by rahardiandj** [comment]
Cool, thanks

**Comment by ankitrm** [comment]
@salvianreynaldi I think it would be a little problematic to have different terraform version in our local vs our AWS infra, especially when we try to run init and plan from our local to ensure our PR's in dev/stg/prod passes. Thoughts?

**Comment by salvianreynaldi** [comment]
HI @ankitrm 
could you try https://github.com/tfutils/tfenv? It might solve the issue of managing multiple terraform versions

**Comment by ankitrm** [comment]
Hello @salvianreynaldi the problem is not with my local, the problem is the terraform version used in our AWS infra

**Pull request closed without merging**
